module NameArrays
	
	CITY_NAMES = ['Koncerdoni',
					'Werthfurd',
					'Belletir',
					'Ethilniy',
					'Fevirshem',
					'Hemmeslehto',
					'Moddlisburuygh',
					'Lyndy',
					'Jidbyrgh',
					'Ectun',
					'Ceilfell ',
					'Gromsby',
					'Pitirbrygh',
					'Werrongtun',
					'Hythi',
					'Suyth Werrin',
					'Myrleyfoild',
					'Pinzenci',
					'Correni ',
					'Eruunshori ',
					'Koncerdoni',
					'Iesthevin ',
					'Myrleyfoild',
					'Erkmynstir',
					'Ceilkork',
					'Purthcewl',
					'Moddlisbruygh',
					'Wontirveli ',
					'Teirnsby',
					'Hertlipuul',
					'Wulfponi',
					'Iestbuyrni',
					'Himphulmi',
					'Bembyrgh',
					'Cuelfill ',
					'Thrii Striems',
					'Ienvirniss',
					'Metluck',
					'Clectun',
					'Kelmenkeltou',
					'Herdirsfoild',
					'Myrifell',
					'Tylweirdrieth',
					'Glenchistir',
					'Trydod ',
					'Niwhem',
					'Erbongtun',
					'Lottli Ovywuud',
					'Ecumb',
					'Llyni',
					'Nurwoch',
					'Weikifoild',
					'Eistun',
					'Swondun',
					'Ilonmylly',
					'Kemuyreske',
					'Jidbyrgh',
					'Konicerdoni',
					'Myrrke',
					'Koniellin',
					'Clerctun',
					'Gerrogoll',
					'Delmirlongtun',
					'Kere\'s Veli ',
					'Tirgerun',
					'Tirgerun',
					'Sexundeli',
					'Pumuveere',
					'Morfoild',
					'Herthweoti',
					'Nentgerth',
					'Wurcistir',
					'Murissliy',
					'Iroth',
					'Irest ',
					'Werthfurd',
					'Erbongtun',
					'Bredfurd',
					'Ceostir',
					'Lirwock',
					'Felcun Hevin',
					'Pindli',
					'Murissliy',
					'Ermegh',
					'Yle\'rii ',
					'Imilli',
					'Uer\'s Rist ',
					'Germsby',
					'Pumuveere',
					'Eldirrdiin ',
					'Werthfurd',
					'Rusileki',
					'Urkniy',
					'Ilonmylly',
					'Tollocuyltry',
					'Cunrostun',
					'Bredfurd',
					'Eychtirmychty',
					'Benruckbyrn',
					'Fellhult',
					'Rusileki',
					'Cymdovuck',
					'Ixitir',
					'Ethilniy',
					'Lertun',
					'Glinerm',
					'Melrtun',
					'Guldcrist ',
					'Kemiireske',
					'Rumsiy',
					'Cerren ',
					'Sexundeli',
					'Konellin',
					'Celchistir',
					'Ruthirhem',
					'Rid Hewk ',
					'MollirVolli',
					'Cliithurpis',
					'Eylisbyry',
					'Wenburni',
					'Wuudponi',
					'Orunhevin',
					'Purtsmuyth',
					'Dregunteol',
					'Firnswurth',
					'Eroe',
					'Ridwetir',
					'Ebirdiin ',
					'Corincistir',
					'Shipshid',
					'Escut',
					'Buruyghtun',
					'Hullyhied ',
					'Hempstied',
					'Eremuri',
					'Hilmforth',
					'Fyrniss',
					'Shop\'s Hevin ',
					'Teiwi',
					'Irustiy ',
					'Myrkwill ',
					'Ketonhente',
					'Myrrke',
					'Potmirdin',
					'Byrreforth',
					'Lerkongi',
					'Tudmurdin',
					'Eddirsfoild',
					'Swondun',
					'Pevv ',
					'Nerncleidre',
					'Furteeri',
					'Hugsfiit ',
					'Hipujuko',
					'Celchirth',
					'Eirmegh',
					'Sneki\'s Cenyun ',
					'Pentmewr',
					'Nentgerw',
					'Ezmer ',
					'Kyyme',
					'Germsby',
					'Nurthpess ',
					'Kyyme',
					'Trydod ',
					'Billichylosh',
					'Morstuni ',
					'Niwshem',
					'Shirfoild',
					'Bruyghtun',
					'Kelmenoimo',
					'Brukin Shoild ',
					'Verosveere',
					'Sorincistir',
					'Liifsodi ',
					'Willsprong ',
					'Jidbyrgh',
					'Hertlipuul',
					'Wulfwetir',
					'Culkork',
					'Rusileki',
					'Cylchith',
					'Lottli Ovywuud',
					'Tylweirdrieth',
					'Fyrniss',
					'Bellonemellerd',
					'Broer Glin ',
					'Celchistir',
					'Kolirth',
					'Durnwoch',
					'Pinkith',
					'Delmirlongtun',
					'Lirwock',
					'Cyllfoild ',
					'Nenclidre',
					'Eshbuyrni',
					'Noshke',
					'Swonfurd',
					'Pren',
					'Purtheithwy']

	DUNGEON_NAMES = ['The Abominable Quarters',
					'The Raging Shelter',
					'The Illusion Maze',
					'Maze of the Neglected Knight',
					'The Voiceless Whimpers Point',
					'Stexohn Overhang',
					'Grotto of the Betrayed Swamp',
					'Xeiz Hideout',
					'Chambers of the Mystic Priest',
					'The Ironbark Cells',
					'The Eastern Caves',
					'The Bottomless Cavity',
					'The Scarlet Quarters',
					'The Wild Cells',
					'The Volcanic Burrows',
					'The Mirage Tunnels',
					'The Eroded Grotto',
					'Dungeon of the Spirit Warrior',
					'Jiqumt Cave',
					'Tombs of the Mythic Priest',
					'The Thief Pits',
					'Qropt Hideout',
					'The Distant Caverns',
					'The Shadow Crypt',
					'Vault of the Burning Cult',
					'Jynom Caverns',
					'The Wild Delves',
					'Catacombs of the Lost Mage',
					'Jynorq Cavern',
					'Ozokx Caverns',
					'The Wondering Lair',
					'The Moaning Chambers',
					'Crypt of the Impostor Warrior',
					'Vrehst Den',
					'Klexup Shelter',
					'The Moaning Vault',
					'Vault of the Destroyed Marsh',
					'The Haunted Maze',
					'Tombs of the Barbaric Soldier',
					'The Dragonclaw Labyrinth',
					'The Wondering Tombs',
					'The Bronze Caverns',
					'Lair of the Secret Basilisk',
					'The Mithril Vault',
					'The Sad Quarters',
					'Pits of the Lost Witch',
					'Quarters of the Dishonored Legion',
					'Tombs of the Chaotic Phoenix',
					'The Phoenix Point',
					'The Diamond Labyrinth',
					'Grotto of the Elemental Ocult',
					'Quarters of the Forsaken Orc',
					'The Silver Labyrinth',
					'The Gleaming Caverns',
					'The Deepwood Delves',
					'Trinyrq Shelter',
					'Caverns of the Frozen Ogre',
					'Grotto of the Storm Knight',
					'Point of the Nameless Lion',
					'The Whispering Haunt',
					'The Misty Dungeon',
					'The Abandoned Chambers',
					'Pits of the Golden Hunter',
					'Quarters of the Death\'s Arachnid',
					'Vault of the Fallen Tiger',
					'The Enchanted Dungeon',
					'Vault of the Doomed Oracle',
					'The Whispering Shadows Vault',
					'Oirt Caves',
					'Delves of the Nightmare Lion',
					'The Destroyed Grotto',
					'The Tormented Delves',
					'Haunt of the Barbaric Spider',
					'The Feared Delves',
					'Lair of the Betrayed Ogre',
					'Chambers of the Hidden Phoenix',
					'The Broken Curse Crypt',
					'The Nether Crypt',
					'The Dread Den',
					'Maze of the Death\'s Desert',
					'Umn Hole',
					'Chambers of the Uncanny Monk',
					'Plocuts Cave',
					'The Frozen Burrows',
					'The White Forest Lair',
					'The Laughing Catacombs',
					'The Invisible Catacombs',
					'The Neverending Labyrinth',
					'Caverns of the Burning Eagle',
					'Zun Hideout',
					'The Silver Quarters',
					'The Silent Subterrane',
					'The Desert Haunt',
					'The Narrow Tombs',
					'The Mithril Mine Cells',
					'The Grizzly Grotto',
					'Grotto of the Shadow Tiger',
					'The Straitened Den',
					'The Twisted Grotto',
					'The Mocking Crypt',
					'Grotto of the Gentle Warrior',
					'Cells of the Secret Paladin',
					'Vliruks Sanctuary',
					'The Living Dead Delves',
					'The Infinite Cave',
					'Uros Hideout',
					'Mal Subterrane',
					'Pits of the Savage Wizard',
					'Caverns of the Nameless Dragon',
					'Crurc Hollow',
					'Plijuhn Overhang',
					'Quarters of the Uncanny Warlord',
					'The Deep Shelter',
					'The Bellowing Tombs',
					'The Obliterated Maze',
					'The Unfathomed Hole',
					'The Wailing Quarters',
					'Vault of the Ghost Scorpion',
					'Dungeon of the Burning Warrior',
					'The Sunken Crypt',
					'The Black Caves',
					'The Raging Dungeon',
					'The Sleeping Maze',
					'Catacombs of the Elemental Monk',
					'The Earth Haunt',
					'Caverns of the Doomed Morass',
					'Haunt of the Hopeless Widow',
					'Grotto of the Storm Wizard',
					'The Living Sanctuary',
					'The Daydream Haunt',
					'Burrows of the Lonely Witch',
					'Lair of the Fallen Bear',
					'Ceht Hollow',
					'The Secret Catacombs',
					'Lair of the Cursed Guardian',
					'The Twilight Dungeon',
					'Quarters of the Secret Paladin',
					'The Brutal Tombs',
					'The Forbidden Pits',
					'Crypt of the Lost Horsemen',
					'The Isolated Catacombs',
					'The Invisible Burrows',
					'The Red Lair',
					'Chambers of the Elemental Phoenix',
					'The Sleeping Haunt',
					'The Lonely Chambers',
					'The Iron Hollows',
					'Pyd Subterrane',
					'The Broken Curse Point',
					'The Burried Cells',
					'Lair of the Uncanny Leopard',
					'The Shadow Point',
					'Glaaw Caves',
					'The Frozen Cells',
					'The White Forest Quarters',
					'Grotto of the Enigmatic Goblin',
					'Bum Hideout',
					'Dungeon of the Uncanny Ocult',
					'The Ironbark Catacombs',
					'The Crystal Lair',
					'Plots Hollows',
					'The Oblivion Grotto',
					'Vault of the Mourning Monk',
					'The Orc Point',
					'The Ghost Haunt',
					'The Wondering Quarters',
					'The Mithril Chambers',
					'The Infernal Labyrinth',
					'Dungeon of the Gentle Knight',
					'The Humongous Cavity',
					'Tombs of the Impostor Phoenix',
					'The Deepwood Burrows',
					'The Gloomy Cavity',
					'Quarters of the Forgotten Guardian',
					'The Bloodlust Lair',
					'Cells of the Renegade Phoenix',
					'The Ethereal Hole',
					'The Smoky Pits',
					'The Steel Lair',
					'Vault of the Rejected King',
					'The Raging Crypt',
					'Telz Cavity',
					'The Buried Burrows',
					'The Haunted Haunt',
					'The Emerald Chambers',
					'The Bleak Haunt',
					'Lair of the Secret Guardian',
					'The Terraced Cells',
					'The Invisible Cells',
					'The Abysmal Cells',
					'Vault of the Shadow Ogre',
					'The Unknown Chambers',
					'Caverns of the Ghost Hunter',
					'Groll Cavern',
					'The Laughing Delves',
					'Flaylf Hole',
					'The Wicked Maze',
					'The Iron Mine Grotto',
					'The Thundering Sanctuary',
					'The Neverending Maze',
					'The Brilliant Tombs',
					'The Scorching Lair',
					'Quarters of the Ancient Bear',
					'Tunnels of the Secret Witch',
					'Natalz Cavity',
					'The Mirrored Dungeon',
					'Lair of the Ancient Queen',
					'Caverns of the Hopeless Bat',
					'The Crystal Haunt',
					'The Soundless Overhang',
					'The Ancient Dungeon',
					'The Distant Burrows',
					'Crypt of the Mourning Leopard',
					'Maze of the Barbaric Legion',
					'Vault of the Death\'s Warlord',
					'Kas Shelter',
					'Qloxipt Hole',
					'The Hungry Chambers',
					'The Tranquil Vault',
					'The Hallucination Tombs',
					'The Lurking Shadow Vault',
					'Vault of the Frozen Ocult',
					'Vlyhq Grotto',
					'The Howling Haunt',
					'Quarters of the Crystal Basilisk',
					'The Turbulent Labyrinth',
					'Tunnels of the Elemental Panther',
					'Cems Hole',
					'The Ethereal Tombs',
					'Labyrinth of the Vanished Serpent',
					'Vlaps Shelter',
					'Clohst Subterrane',
					'The Illusion Dungeon',
					'Quarters of the Whispering Army',
					'The Death Talon Vault',
					'The Wild Delves',
					'The Hallucination Delves',
					'The Death Talon Dungeon',
					'The Eroded Grotto',
					'Tombs of the Cursed Morass',
					'Caverns of the Neglected Tiger',
					'Point of the Burning Knight',
					'The Mirage Labyrinth',
					'Haunt of the Elemental Mountain',
					'The Rocking Point',
					'Haunt of the Lonely Lion',
					'The Boiling Labyrinth',
					'The Cobalt Maze',
					'The Distant Point',
					'The Serene Tombs',
					'Stroks Cavern',
					'The Misty Dungeon',
					'The Mighty Catacombs',
					'Pits of the Poisoned Mountain',
					'Point of the Lonely Ogre',
					'The Specter Cells',
					'Point of the Mystic King',
					'The Straitened Hole',
					'Crypt of the Unspoken Jungle',
					'The False Maze',
					'The Nightmare Grotto',
					'Quarters of the Unspoken Morass',
					'The Obliterated Chambers',
					'The Frozen Tunnels',
					'The Oblivion Tunnels',
					'The Full Moon Cells',
					'The Iron Mine Labyrinth',
					'The Smoky Catacombs',
					'Maze of the Lonely Legion',
					'Point of the Cold Desert',
					'Lair of the Secret Witch',
					'Crypt of the Vanished Mountain',
					'Labyrinth of the Doomed Desert',
					'Cells of the Shrouded King',
					'Haunt of the Death\'s Jungle',
					'The Lion Tooth Tunnels',
					'Pits of the Mythic Oracle',
					'Tombs of the Ruthless Arachnid',
					'The Whispering Pits',
					'The Eternal Agony Tombs',
					'The Peaceful Cave',
					'The Ancient Dungeon',
					'The Bare Delves',
					'The Ogre Caverns',
					'Tunnels of the Vanished Phoenix',
					'Delves of the Shrouded Desert',
					'The Crystal Labyrinth',
					'The Mysterious Chambers',
					'Caverns of the Mourning Mage',
					'Grotto of the Golden Wizard',
					'The Withered Haunt',
					'The Invisible Point',
					'The Unknown Delves',
					'The Winter Cells',
					'The Erased Dungeon',
					'The Cunning Burrows',
					'The Cobalt Cells',
					'The Harmonious Hole',
					'Vlojirf Cavern',
					'Chambers of the Fallen Marsh']

end